Repository chembl/GLaDOS, pull requests merged in 2018-09, with the labels that each got.

#962 Update url after change in es query
  src/glados/static/coffee/SearchResultsApp.coffee
  src/glados/static/coffee/apps/Browsers/BrowserApp.coffee
  src/glados/static/coffee/helpers/URLHelper.coffee
  src/glados/static/coffee/models/SearchModel.coffee
  src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
  src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
  src/glados/static/coffee/models/paginatedCollections/StateSaving/ESCollectionStateSavingFunctions.coffee
  src/glados/static/coffee/models/paginatedCollections/esSchema/FacetingHandler.coffee
  src/glados/static/coffee/routers/MainGladosRouter.coffee
  src/glados/static/coffee/tests/DynamicURLs/URLHelperTests.coffee
  src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/FetchingStateTests.coffee
  src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/StateChangesEvents.coffee
  src/glados/static/coffee/views/Breadcrumb/BreadcrumbsView.coffee
Labels: jenkins-tests-passed

#963 Do not cache visualisations page response
  src/glados/views.py
Labels: jenkins-tests-passed

#964 Fix bugs in url and breadcrumbs updates
  src/glados/static/coffee/helpers/URLHelper.coffee
  src/glados/static/coffee/models/SearchModel.coffee
  src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
  src/glados/static/coffee/views/Breadcrumb/BreadcrumbsView.coffee
  src/glados/static/coffee/views/SearchResults/SearchResultsView.coffee
  src/glados/templates/glados/Handlebars/BreadcrumbSources.html
Labels: jenkins-tests-passed

#970 Autocomplete upgrade in separate branch without slash on name
  src/glados/static/coffee/SearchResultsApp.coffee
  src/glados/static/coffee/models/SearchModel.coffee
  src/glados/static/coffee/models/base/ReportCardEntity.coffee
  src/glados/static/coffee/views/SearchResults/SearchBarAutocompleteView.coffee
  src/glados/static/coffee/views/SearchResults/SearchBarView.coffee
  src/glados/static/coffee/views/SearchResults/SearchResultsView.coffee
  src/glados/static/scss/chembl-style.scss
  src/glados/static/scss/header_style.scss
  src/glados/static/scss/search_results_style.scss
  src/glados/static_files_compiler.py
  src/glados/templates/glados/SearchResultsParts/SearchBarAutocomplete.html
Labels: jenkins-tests-passed

#971 Add first version of query editor
  src/glados/static/coffee/helpers/buttons_helper.coffee
  src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
  src/glados/static/coffee/tests/PaginatedCollections/ESPaginatedCollections/QueryTests.coffee
  src/glados/static/coffee/tests/TestsUtils.coffee
  src/glados/static/coffee/views/Browsers/BrowserMenuView.coffee
  src/glados/static/coffee/views/Browsers/QueryEditorView.coffee
  src/glados/static/coffee/views/PaginatedViews/PaginationFunctions.coffee
  src/glados/static/scss/query_editor_style.scss
  src/glados/templates/glados/Browsers/DefaultBrowserContent.html
  src/glados/templates/glados/Handlebars/BrowserSources.html
  src/glados/templates/glados/Handlebars/Browsers/BrowserSources.html
  src/glados/templates/glados/Handlebars/Browsers/QueryEditorSources.html
  src/glados/templates/glados/Handlebars/CroppedContainers.html
  src/glados/templates/glados/base/css_imports_for_all.html
  src/glados/templates/glados/base/js_imports_for_all.html
Labels: jenkins-tests-passed

#976 Query Editor: add links to FAQs in gitbook.
  src/glados/templates/glados/Handlebars/Browsers/QueryEditorSources.html
  src/glados/urls.py
Labels: jenkins-tests-failed

#977 Fix target relations links
  src/glados/static/coffee/models/TargetRelation.coffee
  src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
  src/glados/static/coffee/models/paginatedCollections/SpecificFlavours/TargetRelationsList.coffee
  src/glados/templates/glados/base/js_imports_for_all.html
Labels: jenkins-tests-passed

#982 Marvin License: try to add license file
  src/glados/static/marvinjs/editorws.html
  src/glados/static/marvinjs/m4js
Labels: jenkins-tests-queued

#983 Marvin JS license: try common license file
  src/glados/static/marvinjs/editorws.html
Labels: jenkins-tests-queued
