Repository chembl/GLaDOS, pull requests merged in 2019-03, with the labels that each got.

#1044 Implement blast search
  src/glados/api/dynamic-downloads/downloads_manager.py
  src/glados/api/list_pagination/pagination_helper.py
  src/glados/api/sssearch/blast.py
  src/glados/api/sssearch/search_manager.py
  src/glados/api/sssearch/structure.py
  src/glados/api/sssearch/structure_and_sequence_search_manager.py
  src/glados/api/sssearch/urls.py
  src/glados/migrations/0011_auto_20190227_0945.py
  src/glados/migrations/0012_sssearchjob_error_message.py
  src/glados/migrations/0013_auto_20190301_1427.py
  src/glados/migrations/0014_auto_20190301_1513.py
  src/glados/migrations/0016_auto_20190301_1622.py
  src/glados/migrations/0017_remove_downloadjob_id.py
  src/glados/migrations/0018_remove_downloadjob_id.py
  src/glados/models.py
  src/glados/static/coffee/SearchResultsApp.coffee
  src/glados/static/coffee/Settings.coffee
  src/glados/static/coffee/apps/Main/MainGladosApp.coffee
  src/glados/static/coffee/helpers/SequenceSearchHelper.coffee
  src/glados/static/coffee/models/Search/BLASTParamsModel.coffee
  src/glados/static/coffee/models/Search/StructureSearchModel.coffee
  src/glados/static/coffee/models/Target.coffee
  src/glados/static/coffee/models/paginatedCollections/Settings.coffee
  src/glados/static/coffee/routers/MainGladosRouter.coffee
  src/glados/static/coffee/views/SearchResults/SSQueryView.coffee
  src/glados/static/coffee/views/SearchResults/SearchBarView.coffee
  src/glados/static/coffee/views/SearchResults/SequenceQueryView.coffee
  src/glados/static/coffee/views/SearchResults/SequenceSearchView.coffee
  src/glados/static/coffee/views/SearchResults/StructureQueryView.coffee
  src/glados/static/scss/sequence_search_styles.scss
  src/glados/static/scss/structure_search_style.scss
  src/glados/templates/glados/Handlebars/CommonSources.html
  src/glados/templates/glados/Handlebars/LazilyLoaded/Search/SearchSources.html
  src/glados/templates/glados/Handlebars/SequenceSearch/SequenceSearchSources.html
  src/glados/templates/glados/Handlebars/SubstructureSearchResults/SubstructureSearchResultsSources.html
  src/glados/templates/glados/SearchResultsParts/SearchBar.html
  src/glados/templates/glados/base/js_imports_for_all.html
  src/glados/urls.py
Labels: jenkins-tests-passed

#1046 BLAST Search: fix bug when search parameters are edited
  src/glados/migrations/0001_initial.py
  src/glados/static/coffee/views/SearchResults/SequenceSearchView.coffee
Labels: jenkins-tests-failed

#1047 Main page: tweak visualisation order base on usage statistics
  src/glados/static/coffee/views/MainPage/VisualisationsWithCaptionsView.coffee
Labels: jenkins-tests-failed

#1049 URL: create redirection for old report card urls
  src/glados/urls.py
Labels: jenkins-tests-passed

#1052 Drugs: add withdrawn class to additional columns and download columns
  src/glados/static/coffee/models/Compound/Drug.coffee
  src/glados/static/coffee/tests/DownloadsTest.coffee
Labels: jenkins-tests-failed

#1054 Add withdrawn fields to optional filters
  src/glados/static/coffee/models/paginatedCollections/esSchema/CompoundSchema.coffee
Labels: jenkins-tests-passed

#1056 Update web services documentation url
  src/glados/templates/glados/base/chembl_header.html
  src/glados/urls.py
Labels: jenkins-tests-passed

#1057 Fix drug indications mechanisms of action downloads
  src/glados/api/dynamic-downloads/columns_parser.py
  src/glados/api/dynamic-downloads/downloads_manager.py
  src/glados/static/coffee/models/Compound/DrugIndication.coffee
  src/glados/static/coffee/models/Compound/MechanismOfAction.coffee
Labels: jenkins-tests-passed

#1059 Downloads length: increase length of id property to 100 characters
  src/glados/migrations/0002_auto_20190319_1420.py
  src/glados/models.py
Labels: jenkins-tests-failed

#1060 Fix state urls (drugs, mechanisms of action, drug indications)
  src/glados/static/coffee/helpers/URLHelper.coffee
  src/glados/static/coffee/models/Compound/Drug.coffee
  src/glados/static/coffee/models/Compound/DrugIndication.coffee
  src/glados/static/coffee/models/Compound/MechanismOfAction.coffee
Labels: jenkins-tests-passed

#1061 State URLs: restore correctly state when hidden filters selected
  src/glados/static/coffee/models/paginatedCollections/PaginatedCollectionFactory.coffee
Labels: jenkins-tests-passed

#1063 Elasticsearch 6.6.1
  configurations/config_example.yml
  configurations/default_travis_config.yml
  configurations/minimal_dev_config.yml
  requirements.txt
  src/glados/api/list_pagination/pagination_helper.py
  src/glados/api/sssearch/structure.py
  src/glados/es_connection.py
  src/glados/es_models.py
  src/glados/grammar/search_parser.py
  src/glados/schema_tags_generator.py
  src/glados/settings.py
  src/glados/settings_context.py
  src/glados/static/coffee/ChemUtils.coffee
  src/glados/static/coffee/Settings.coffee
  src/glados/static/coffee/Utils.coffee
  src/glados/static/coffee/models/Activity/ActivityAggregationMatrix.coffee
  src/glados/static/coffee/models/Aggregations/Aggregation.coffee
  src/glados/static/coffee/models/Assay.coffee
  src/glados/static/coffee/models/CellLine.coffee
  src/glados/static/coffee/models/Compound.coffee
  src/glados/static/coffee/models/Document.coffee
  src/glados/static/coffee/models/SearchModel.coffee
  src/glados/static/coffee/models/Target.coffee
  src/glados/static/coffee/models/Tissue.coffee
  src/glados/static/coffee/models/paginatedCollections/ESPaginatedQueryCollection.coffee
  src/glados/static/coffee/models/paginatedCollections/Settings.coffee
  src/glados/static/coffee/tests/Compound/CompoundTest.coffee
  src/glados/static/coffee/tests/Document/DocumentTest.coffee
  src/glados/static/coffee/tests/PaginatedCollections/PaginatedCollectionTest.coffee
  src/glados/static/coffee/tests/TargetTest.coffee
  src/glados/static/coffee/tests/UtilsTest.coffee
  src/glados/static/coffee/views/Compound/MetabolismView.coffee
  src/glados/templates/glados/base/js_imports_for_all.html
  src/glados/templates/glados/compoundReportCard.html
Labels: jenkins-tests-passed

#1064 Make share button more visible
  configurations/default_travis_config.yml
  configurations/minimal_dev_config.yml
  src/glados/api/dynamic-downloads/downloads_manager.py
  src/glados/api/list_pagination/pagination_helper.py
  src/glados/api/sssearch/blast.py
  src/glados/api/sssearch/structure.py
  src/glados/api/url_shortening/__init__.py
  src/glados/api/url_shortening/url_shortener.py
  src/glados/api/url_shortening/urls.py
  src/glados/api/urls.py
  src/glados/es_connection.py
  src/glados/es_models.py
  src/glados/grammar/search_parser.py
  src/glados/manage.py
  src/glados/migrations/0003_tinyurl_expires.py
  src/glados/models.py
  src/glados/settings.py
  src/glados/static/coffee/Settings.coffee
  src/glados/static/coffee/apps/BreadcrumbApp.coffee
  src/glados/static/coffee/apps/Main/MainGladosApp.coffee
  src/glados/static/coffee/helpers/SharePageHelper.coffee
  src/glados/static/coffee/helpers/URLHelper.coffee
  src/glados/static/coffee/models/Search/BLASTParamsModel.coffee
  src/glados/static/coffee/models/SharePage/SharePageModel.coffee
  src/glados/static/coffee/views/Breadcrumb/BreadcrumbsView.coffee
  src/glados/static/coffee/views/SearchResults/SearchBarView.coffee
  src/glados/static/coffee/views/SharePage/SharePageView.coffee
  src/glados/static/scss/header_style.scss
  src/glados/templates/glados/Handlebars/BreadcrumbSources.html
  src/glados/templates/glados/Handlebars/CommonSources.html
  src/glados/templates/glados/Handlebars/SharePage/SharePageSources.html
  src/glados/templates/glados/base/chembl_header.html
  src/glados/templates/glados/base/js_imports_for_all.html
  src/glados/url_shortener/url_shortener.py
  src/glados/urls.py
  src/glados/usage_statistics/__init__.py
  src/glados/usage_statistics/glados_server_statistics.py
  src/glados/utils/__init__.py
  src/glados/utils/manage_shortened_urls.py
  src/glados/utils_refactor.py
  src/glados/views.py
Labels: jenkins-tests-failed

#1065 Set up google analytics
  src/glados/templates/glados/base/base_layout.html
  src/glados/templates/glados/base/google_analytics.html
  src/glados/templates/glados/base/hotjar_analytics.html
  src/glados/templates/glados/base/minimum_layout.html
  src/glados/templates/glados/marvin_search_fullscreen.html
Labels: jenkins-tests-queued

#1066 Urls redirection: create a function to handle report card redirects
  src/glados/old_urls_redirector.py
  src/glados/urls.py
Labels: jenkins-tests-failed

#1067 Fix api urls for interface switch
  src/glados/settings.py
  src/glados/static/coffee/Settings.coffee
  src/glados/static/coffee/models/Search/BLASTParamsModel.coffee
  src/glados/static/coffee/models/Search/StructureSearchModel.coffee
  src/glados/static/coffee/models/ServerSideDownloads/DownloadModel.coffee
  src/glados/static/coffee/tests/ServerSideDownloads/ServerSideDownloadsTest.coffee
  src/glados/urls.py
  util/http.d/apache_config_template.txt
Labels: jenkins-tests-queued

#1068 fix beta and old_interface urls
  src/glados/urls.py
  util/http.d/apache_config_template.txt
Labels: jenkins-tests-queued

#1069 fix to match new style of id filtering in relationships for ES6
  src/glados/static/coffee/TissueReportCardApp.coffee
  src/glados/static/coffee/assayReportCardApp.coffee
  src/glados/static/coffee/cellLineReportCardApp.coffee
  src/glados/static/coffee/compoundReportCardApp.coffee
  src/glados/static/coffee/configs/ReportCards/Compound/AssaySummaryPieConfig.coffee
  src/glados/static/coffee/configs/ReportCards/Compound/TargetSummaryPieConfig.coffee
  src/glados/static/coffee/documentReportCardApp.coffee
  src/glados/static/coffee/models/Activity/ActivityAggregationMatrix.coffee
  src/glados/static/coffee/models/Assay.coffee
  src/glados/static/coffee/models/CellLine.coffee
  src/glados/static/coffee/models/Compound.coffee
  src/glados/static/coffee/models/Document.coffee
  src/glados/static/coffee/models/Target.coffee
  src/glados/static/coffee/models/Tissue.coffee
  src/glados/static/coffee/targetReportCardApp.coffee
  src/glados/static/coffee/tests/Compound/CompoundTest.coffee
  src/glados/static/coffee/tests/Document/DocumentTest.coffee
  src/glados/static/coffee/tests/MatrixTest.coffee
  src/glados/static/coffee/tests/TargetTest.coffee
Labels: jenkins-tests-passed

#1079 update example configs
  configurations/config_example.yml
  configurations/default_travis_config.yml
  configurations/minimal_dev_config.yml
Labels: jenkins-tests-passed

#1081 Update privacy police url
  src/glados/templates/glados/base/data_protection_banner.html
Labels: jenkins-tests-passed
